[project]
name = 'Decentralized-Mining-Asteroid-Resource-Extraction'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mining-entity-verification]
path = 'contracts/mining-entity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-processing]
path = 'contracts/resource-processing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
